#
# Welcome to OldDays configuration file.
#

disabled-worlds:
  - testworld

disable:
  sprint: true
  hunger: true
  auto-heal: true
  breeding: true
  rotated-logs: true
  new-death-messages: true
  raw-chicken-poison: true
  
disable-xp:
  block-break: true
  entity-kill: true
  player-death: true
  furnace-smelt: true
  fishing: true
  exp-bottle: true
  clear-on-join: true
  
disable-spawn-list:
  # http://jd.bukkit.org/dev/apidocs/org/bukkit/entity/EntityType.html
  - ENDERMAN
  - SILVERFISH
  - WITHER
  - WITHER_SKULL
  - WITCH
  - MUSHROOM_COW
  - BAT
  - CAVE_SPIDER
  - OCELOT
  - VILLAGER
  - IRON_GOLEM
  - MAGMA_CUBE
  - BLAZE
  - SNOWMAN
  - HORSE

disable-spawn:
  wither-skeleton: true
  zombie-villager: true
  baby-zombies: true
  baby-animals-from-eggs: true
  # Completely prevent spawning mobs from mob eggs.
  from-mob-eggs: true
  
disable-new-drops:
  # Zombie only drop feather.
  zombie: true
  chicken: true
  cow: true
  spider: true
  # Pigs will drop 0-2 porks instead of 1-3
  pig: true
  ghast: true
  # Zombie pigman will drop 0-2 Cooked Porkchop
  zombie-pigman: true
  # This makes blaze drop 0-2 glowstone dust
  blaze: true

disable-open:
  # http://jd.bukkit.org/dev/apidocs/org/bukkit/Material.html
  - ENCHANTMENT_TABLE
  - ANVIL
  - DROPPER
  - HOPPER
  - HOPPER_MINECART
  - BEACON
  - ENDER_CHEST
  - BREWING_STAND
  - CAULDRON
  - COMMAND

disable-placing:
  string: true
  cocoa-beans: true

disable-enchant:
  book: true

disable-inventory:
  # http://jd.bukkit.org/dev/apidocs/org/bukkit/event/inventory/ClickType.html
  click-types:
    - SHIFT_LEFT
    - SHIFT_RIGHT
    - NUMBER_KEY
    - CONTROL_DROP
  # http://jd.bukkit.org/dev/apidocs/org/bukkit/event/inventory/InventoryAction.html
  actions:
    - COLLECT_TO_CURSOR
    - CONTROL_DROP

disable-recipes:
  horse-update: true
  redstone-update: true
  pretty-scary-update: true
  one-point-three-update: true
  one-point-two-update: true
  
  colored-wood-planks: true
  
disable-other:
  zombie-break-door: true
  villager-trading: true
  snow-layers: true
  nether-wart-farming-outside-nether: true
  ender-pearl: true
  zombie-sieges: true
  entity-entering-portal: true
  monsters-wearing-armor: true
  zombie-setting-player-on-fire: true
  potion-effects: true
  # Disable that buggy "disconnect.spam" vanilla feature
  spam-kick: true
  fly-kick: true
  item-repair: true
  spider-with-potions: true
  horse-rightclick: true
  zombie-reinforcements: true
  
enable:
  old-bow: true
  # Makes diamond sword damage 5 hearts instead of 3,5 and iron sword 4 hearts instead of 3
  old-sword-damage: true
  # Old sheep and zombie health
  old-mob-health: true
  # Note: You must disable hunger if you want that feature to be enabled! ( Set hunger to "true" )
  instant-food: true
  instant-bonemeal: true
  # Unable to mine quartz ore, on click converts to netherrack.
  quartz-ore-to-netherrack: true
  getting-wool-by-sheep-punching: true
  punching-tnt: true
  # When breaking, player lose 1 hearts.  Player can also die if he has =< 1 hearts.
  old-cactus: true
  # There are more animals, and they can despawn.
  old-animal-spawn: true
  old-adventure-mode: true
  old-strength-potion: true
  # No new flowers, slightly different behavior. Also disables duping double block flowers and bonemeal on tall grass making it double block.
  old-bonemeal-on-grass: true
  
messages: 
  # Set to "none" to disable message.
  sprint: none
  trade: "&7Trading is &cdisabled&7. Find another way to obtain items."
  block-click: "&7This block has no function."
  block-place: "&7Placing %BLOCK was &cdisabled &7on this server."
  block-nether-warth: "&7You can only farm nether wart in &cNether."
  block-spawner-eggs: "&7Using &cspawner eggs &7is not allowed."

misc:
  drop-chances:
    crops:
      first-stage: 0.2
      second-stage: 0.3
      third-stage: 0.55
      fourth-stage: 0.75
  # You must have ProtocolLib enabled to use following features. NB: *In Beta!*
  packets:
    # Set 'enabled' to false to turn off all packet features.
    enabled: true
    disable-player-sample-in-motd: true
    disable-chest-sound-and-animation: true
    disable-fall-particles: true
    disable-bonemeal-particles: true

advanced:
  update-config: true
  nether-detection: normal
  tree-physics: true
  # Force hunger bar at 3 hearts. Not recommended anymore.
  alternative-nosprint: false
  debug: false
    
# Do not change version number!
version: 1.4.1